/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms2;

/**
 *
 * @author Acer
 */
public class layout extends javax.swing.JFrame {

    /**
     * Creates new form layout
     */
    public layout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        del = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ASSIGNMENT NAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(13, 18, 213, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUBMISSION DATE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(13, 90, 213, 28);

        subject.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        subject.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        jPanel1.add(subject);
        subject.setBounds(268, 14, 161, 28);

        date.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date);
        date.setBounds(268, 94, 161, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 75, 464, 143);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NAME");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(34, 47, 131, 29);

        del.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel2.add(del);
        del.setBounds(239, 50, 153, 28);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(534, 75, 439, 143);

        Add.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(63, 225, 149, 64);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(403, 225, 149, 64);

        delete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(735, 225, 149, 64);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("ADD ASSIGNMENT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(86, 13, 297, 44);

        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.setToolTipText("");
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 320, 990, 30);

        exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(434, 693, 126, 61);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("DELETE ASSIGNMENT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(582, 13, 350, 44);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/todo","root","rithwik")) {
                Statement stmt = conn.createStatement();
                String sub = subject.getText();
                String dat = date.getText();
                stmt.addBatch("insert into assignment values('"+sub+"','"+dat+"')");
                stmt.executeBatch();
                ResultSet re = stmt.executeQuery("select * from assignment where date >= curdate() order by date");

                DefaultTableModel model = new DefaultTableModel(new String[]{"sub", "dat"}, 0);
                while(re.next())
                {
                    String d = re.getString("subject");
                    String e = re.getString("date");
                    //String f = rs.getString("dueDate");
                    model.addRow(new Object[]{d, e});
                }
                table.setModel(model);

                conn.close();
            }
        }
        catch(ClassNotFoundException | SQLException e){ System.out.println(e);}
    }//GEN-LAST:event_AddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            }catch (ClassNotFoundException e) {}
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/todo","root","rithwik")) {
                System.out.println("Connection is created successfully:");
                Statement   stmt = conn.createStatement();
                String dt = del.getText();
                //Query
                ResultSet re = stmt.executeQuery("select * from assignment where date >= curdate() order by date");
                //Table
                DefaultTableModel model = new DefaultTableModel(new String[]{"subj", "datee"}, 0);
                while(re.next())
                {
                    String d = re.getString("subject");
                    String e = re.getString("date");
                    model.addRow(new Object[]{d, e});
                }
                table.setModel(model);

                conn.close();
            }
        } catch (SQLException excep) {}
        catch (Exception excep) {}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            }catch (ClassNotFoundException e) {}
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/todo","root","rithwik")) {
                System.out.println("Connection is created successfully:");
                Statement   stmt = conn.createStatement();
                String dt = del.getText();
                //Query
                String query1="delete from assignment where subject='"+dt+"'";
                stmt.addBatch(query1);
                stmt.executeBatch();
                ResultSet re = stmt.executeQuery("select * from assignment where date >= curdate() order by date");
                //Table
                DefaultTableModel model = new DefaultTableModel(new String[]{"sub", "dat"}, 0);
                while(re.next())
                {
                    String d = re.getString("subject");
                    String e = re.getString("date");
                    model.addRow(new Object[]{d, e});
                }
                table.setModel(model);

                conn.close();
            }
        } catch (SQLException excep) {}
        catch (Exception excep) {}
    }//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField date;
    private javax.swing.JTextField del;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField subject;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
